### PR TITLE
Minecraft 1.20.1

### PR DESCRIPTION
**Pull request by loehnertj**
My kids keep asking for it, so I'd like to see this Mod on current Minecraft :-)

I have no previous experience with modding whatsoever, but I managed to make it work ~~95%~~ 100% on MC 1.20.1. I would be very happy if you could review it.

~~TODO: The one problem that persists is that when Mirror or radial modifier is active, the mirror plane / axis lines are rendered wrong. Apparently they wrongly use viewport coords instead of world coords. I couldn't figure out how to fix this.~~ / EDIT: Fixed

On a sidenote, I also made the "Toggle replace mode" hotkey work again.

Requires update of the gradle-curseforge-plugin: just adding in the new versions as Enum constants.

### CODE REVIEW

**Comment by huskcasaca** [comment]
Thanks. I will merge this pull request after I finish the development of v2.0.0.

**Comment by loehnertj** [comment]
Actually, my intention was more to provide something working "for the crowds" right now, while version 2 is in the works. Readymade .jar file is here: https://github.com/loehnertj/effortless-fabric/releases/tag/version%2F1.6.3-1.20.1, you're free to take it and publish it on CF.

I'm not sure if merging into 2.0.0 is even possible, considering the amount of changes there. However you can of course look through my commits to see what changes are needed. Or I can also have a look at the 2.0.0 branch.

Best regards :-)

**Comment by huskcasaca** [comment]
Sure

**Comment by loehnertj** [comment]
I made a port to 1.20.2 today -> see my Github release page.

Maybe you can announce on Curseforge - for unknown reasons it doesn't let me post a comment.

**Comment by huskcasaca** [comment]
Added

**Pull request closed without merging**
